title: bydips
url: "https://bydips.com"
plugins:
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:slug/

tracking:
  gtag_id: "G-2DQQ2PNPYK"
